[program:civin-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/civin/backend/artisan queue:work redis --queue=default --sleep=3 --tries=3 --backoff=5 --timeout=90 --max-time=3600
directory=/var/www/civin/backend
user=www-data
numprocs=2
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=3600
redirect_stderr=true
stdout_logfile=/var/www/civin/backend/storage/logs/worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
environment=APP_ENV="production"
